package com.kennedy.forge.ui.screens.portfolio

// ─────────────────────────────────────────────────────────────────
//  DEPENDENCIES (already in project)
//  implementation(platform("com.google.firebase:firebase-bom:33.1.0"))
//  implementation("com.google.firebase:firebase-auth-ktx")
//  implementation("com.google.firebase:firebase-database-ktx")
//  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.8.1")
//  implementation("io.coil-kt:coil-compose:2.6.0")
// ─────────────────────────────────────────────────────────────────

import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.*
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.material3.ripple
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.*
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalInspectionMode
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import androidx.navigation.NavController
import androidx.navigation.compose.rememberNavController
import coil.compose.AsyncImage
import com.google.firebase.Firebase
import com.google.firebase.auth.auth
import com.google.firebase.database.*
import com.kennedy.forge.ui.theme.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext

// ─────────────────────────────────────────────────────────────────
//  MODELS
// ─────────────────────────────────────────────────────────────────

data class PortfolioItem(
    val id: String            = "",
    val title: String         = "",
    val category: String      = "",
    val description: String   = "",
    val imageUrl: String       = "",   // Cloudinary URL or empty
    val tags: List<String>    = emptyList(),
    val featured: Boolean     = false,
    val createdAt: Long       = System.currentTimeMillis()
)

data class PortfolioMeta(
    val uid: String           = "",
    val headline: String      = "",   // e.g. "Creative Designer & Storyteller"
    val tagline: String       = "",   // 1-liner used in pitch
    val theme: String         = "dark",
    val isPublished: Boolean  = false,
    val autoGenerated: Boolean = false,
    val updatedAt: Long       = System.currentTimeMillis()
)

enum class PortfolioTab { WORKS, BUILDER, PREVIEW }

// ─────────────────────────────────────────────────────────────────
//  FIREBASE HELPERS
// ─────────────────────────────────────────────────────────────────

private suspend fun loadPortfolioMeta(uid: String): PortfolioMeta? =
    try {
        val snap = Firebase.database.reference.child("users").child(uid)
            .child("portfolio").child("meta").get().await()
        snap.getValue(PortfolioMeta::class.java)
    } catch (e: Exception) { null }

private suspend fun loadPortfolioItems(uid: String): List<PortfolioItem> =
    try {
        val snap = Firebase.database.reference.child("users").child(uid)
            .child("portfolio").child("items").get().await()
        snap.children.mapNotNull { it.getValue(PortfolioItem::class.java) }
            .sortedByDescending { it.createdAt }
    } catch (e: Exception) { emptyList() }

private suspend fun savePortfolioMeta(uid: String, meta: PortfolioMeta): Result<Unit> =
    runCatching {
        Firebase.database.reference.child("users").child(uid)
            .child("portfolio").child("meta").setValue(meta).await()
    }

private suspend fun savePortfolioItem(uid: String, item: PortfolioItem): Result<Unit> =
    runCatching {
        val ref = if (item.id.isEmpty())
            Firebase.database.reference.child("users").child(uid).child("portfolio").child("items").push()
        else
            Firebase.database.reference.child("users").child(uid).child("portfolio").child("items").child(item.id)
        ref.setValue(item.copy(id = ref.key ?: item.id)).await()
    }

private suspend fun deletePortfolioItem(uid: String, itemId: String): Result<Unit> =
    runCatching {
        Firebase.database.reference.child("users").child(uid)
            .child("portfolio").child("items").child(itemId).removeValue().await()
    }

private suspend fun toggleFeatured(uid: String, item: PortfolioItem): Result<Unit> =
    runCatching {
        Firebase.database.reference.child("users").child(uid)
            .child("portfolio").child("items").child(item.id)
            .child("featured").setValue(!item.featured).await()
    }

/** Reads the user profile and uploads, then builds a PortfolioMeta automatically */
private suspend fun autoGeneratePortfolio(uid: String): Result<PortfolioMeta> = runCatching {
    val profileSnap = Firebase.database.reference.child("users").child(uid)
        .child("profile").get().await()
    val name       = profileSnap.child("name").getValue(String::class.java) ?: "Creator"
    val profession = profileSnap.child("profession").getValue(String::class.java) ?: "Creative"
    val bio        = profileSnap.child("bio").getValue(String::class.java) ?: ""

    val generated = PortfolioMeta(
        uid           = uid,
        headline      = "$profession · Visual Storyteller · Problem Solver",
        tagline       = if (bio.isNotBlank()) bio.take(120) else "Crafting bold ideas into unforgettable experiences.",
        theme         = "dark",
        isPublished   = false,
        autoGenerated = true
    )
    savePortfolioMeta(uid, generated).getOrThrow()
    generated
}

// ─────────────────────────────────────────────────────────────────
//  MAIN SCREEN
// ─────────────────────────────────────────────────────────────────

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PortfolioBuilderScreen(navController: NavController) {

    val isPreview = LocalInspectionMode.current
    val scope     = rememberCoroutineScope()
    val uid       = if (isPreview) "preview_uid" else Firebase.auth.currentUser?.uid ?: ""

    var activeTab       by remember { mutableStateOf(PortfolioTab.BUILDER) }
    var meta            by remember { mutableStateOf(PortfolioMeta()) }
    var items           by remember { mutableStateOf<List<PortfolioItem>>(emptyList()) }
    var isLoading       by remember { mutableStateOf(!isPreview) }
    var isSaving        by remember { mutableStateOf(false) }
    var isGenerating    by remember { mutableStateOf(false) }
    var errorMsg        by remember { mutableStateOf("") }
    var showAddDialog   by remember { mutableStateOf(false) }
    var editingItem     by remember { mutableStateOf<PortfolioItem?>(null) }
    var showDeleteId    by remember { mutableStateOf("") }

    // ── Preview mock data ─────────────────────────────────────────
    LaunchedEffect(Unit) {
        if (isPreview) {
            meta  = PortfolioMeta(uid = "preview", headline = "Creative Designer & Visual Storyteller",
                tagline = "Crafting bold ideas into unforgettable experiences.", isPublished = true)
            items = listOf(
                PortfolioItem("1", "Brand Identity – Forge", "Branding", "Full visual identity system", featured = true),
                PortfolioItem("2", "Motion UI Kit",          "Motion",   "Micro-interaction library",  featured = false),
                PortfolioItem("3", "Editorial Layout",       "Print",    "Magazine spread design",     featured = true)
            )
            isLoading = false
            return@LaunchedEffect
        }
        if (uid.isEmpty()) { isLoading = false; return@LaunchedEffect }
        val loadedMeta  = loadPortfolioMeta(uid)
        val loadedItems = loadPortfolioItems(uid)
        meta    = loadedMeta ?: PortfolioMeta(uid = uid)
        items   = loadedItems
        isLoading = false
    }

    Scaffold(
        containerColor = BackgroundMain,
        topBar = {
            CenterAlignedTopAppBar(
                title = {
                    Text("Portfolio Builder", fontWeight = FontWeight.Black,
                        letterSpacing = 0.5.sp, color = TextPrimary)
                },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, null, tint = TextPrimary)
                    }
                },
                actions = {
                    // Publish toggle
                    AnimatedContent(targetState = meta.isPublished, label = "pub") { published ->
                        Box(
                            modifier = Modifier
                                .clip(RoundedCornerShape(10.dp))
                                .background(if (published) SoftGreen.copy(0.15f) else BackgroundSecondary)
                                .clickable {
                                    val updated = meta.copy(isPublished = !meta.isPublished)
                                    meta = updated
                                    if (uid.isNotEmpty()) scope.launch { savePortfolioMeta(uid, updated) }
                                }
                                .padding(horizontal = 10.dp, vertical = 6.dp)
                        ) {
                            Text(
                                if (published) "Published" else "Draft",
                                color      = if (published) SoftGreen else TextSecondary,
                                fontSize   = 11.sp,
                                fontWeight = FontWeight.Bold
                            )
                        }
                    }
                    Spacer(Modifier.width(8.dp))
                },
                colors = TopAppBarDefaults.centerAlignedTopAppBarColors(containerColor = BackgroundMain)
            )
        }
    ) { padding ->

        if (isLoading) {
            Box(Modifier.fillMaxSize().padding(padding), contentAlignment = Alignment.Center) {
                CircularProgressIndicator(color = GoldPrimary)
            }
            return@Scaffold
        }

        Column(modifier = Modifier.fillMaxSize().padding(padding)) {

            // ── TAB SWITCHER ──────────────────────────────────────
            PortfolioTabSwitcher(activeTab = activeTab, onSelect = { activeTab = it })

            // ── CONTENT ───────────────────────────────────────────
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .verticalScroll(rememberScrollState())
                    .padding(bottom = 32.dp)
            ) {
                AnimatedContent(
                    targetState   = activeTab,
                    transitionSpec = { fadeIn(tween(200)) togetherWith fadeOut(tween(200)) },
                    label         = "tab"
                ) { tab ->
                    when (tab) {

                        // ── WORKS TAB ─────────────────────────────
                        PortfolioTab.WORKS -> WorksTabContent(
                            items        = items,
                            onAddClick   = { showAddDialog = true; editingItem = null },
                            onEditClick  = { editingItem = it; showAddDialog = true },
                            onDeleteClick = { showDeleteId = it.id },
                            onFeatureClick = { item ->
                                scope.launch {
                                    toggleFeatured(uid, item)
                                    items = items.map { if (it.id == item.id) it.copy(featured = !it.featured) else it }
                                }
                            }
                        )

                        // ── BUILDER TAB ───────────────────────────
                        PortfolioTab.BUILDER -> BuilderTabContent(
                            meta          = meta,
                            isGenerating  = isGenerating,
                            isSaving      = isSaving,
                            errorMsg      = errorMsg,
                            onMetaChange  = { meta = it },
                            onSave        = {
                                isSaving = true; errorMsg = ""
                                scope.launch {
                                    savePortfolioMeta(uid, meta).fold(
                                        onSuccess = { withContext(Dispatchers.Main) { isSaving = false } },
                                        onFailure = { e -> withContext(Dispatchers.Main) { isSaving = false; errorMsg = e.message ?: "Save failed" } }
                                    )
                                }
                            },
                            onAutoGenerate = {
                                isGenerating = true; errorMsg = ""
                                scope.launch {
                                    autoGeneratePortfolio(uid).fold(
                                        onSuccess = { generated -> withContext(Dispatchers.Main) { meta = generated; isGenerating = false } },
                                        onFailure = { e -> withContext(Dispatchers.Main) { isGenerating = false; errorMsg = e.message ?: "Generation failed" } }
                                    )
                                }
                            }
                        )

                        // ── PREVIEW TAB ───────────────────────────
                        PortfolioTab.PREVIEW -> PreviewTabContent(
                            meta       = meta,
                            items      = items,
                            onPitchClick = { navController.navigate("pitch_view") }
                        )
                    }
                }
            }
        }

        // ── ADD / EDIT DIALOG ─────────────────────────────────────
        if (showAddDialog) {
            AddEditItemDialog(
                initial    = editingItem,
                onDismiss  = { showAddDialog = false; editingItem = null },
                onSave     = { item ->
                    showAddDialog = false
                    scope.launch {
                        savePortfolioItem(uid, item).fold(
                            onSuccess = {
                                val refreshed = loadPortfolioItems(uid)
                                withContext(Dispatchers.Main) { items = refreshed }
                            },
                            onFailure = { e ->
                                withContext(Dispatchers.Main) { errorMsg = e.message ?: "Save failed" }
                            }
                        )
                    }
                }
            )
        }

        // ── DELETE CONFIRMATION ───────────────────────────────────
        if (showDeleteId.isNotEmpty()) {
            AlertDialog(
                onDismissRequest  = { showDeleteId = "" },
                title             = { Text("Remove work?", fontWeight = FontWeight.Bold) },
                text              = { Text("This will permanently remove this item from your portfolio.") },
                confirmButton     = {
                    TextButton(onClick = {
                        val id = showDeleteId; showDeleteId = ""
                        scope.launch {
                            deletePortfolioItem(uid, id)
                            items = items.filter { it.id != id }
                        }
                    }) { Text("Remove", color = Error, fontWeight = FontWeight.Bold) }
                },
                dismissButton     = {
                    TextButton(onClick = { showDeleteId = "" }) { Text("Cancel", color = TextSecondary) }
                },
                containerColor    = CardBackground
            )
        }
    }
}

// ─────────────────────────────────────────────────────────────────
//  TAB SWITCHER
// ─────────────────────────────────────────────────────────────────

@Composable
private fun PortfolioTabSwitcher(activeTab: PortfolioTab, onSelect: (PortfolioTab) -> Unit) {
    val tabs = listOf(PortfolioTab.WORKS to "Works", PortfolioTab.BUILDER to "Builder", PortfolioTab.PREVIEW to "Preview")
    Row(
        modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 12.dp)
            .clip(RoundedCornerShape(14.dp)).background(BackgroundSecondary)
    ) {
        tabs.forEach { (tab, label) ->
            val active = activeTab == tab
            Box(
                modifier = Modifier.weight(1f).clip(RoundedCornerShape(12.dp))
                    .background(if (active) Brush.horizontalGradient(listOf(GoldPrimary, GoldAccent))
                    else Brush.horizontalGradient(listOf(Color.Transparent, Color.Transparent)))
                    .clickable { onSelect(tab) }.padding(vertical = 10.dp),
                contentAlignment = Alignment.Center
            ) {
                Text(label,
                    color = if (active) DarkSurface else TextSecondary,
                    fontWeight = if (active) FontWeight.Bold else FontWeight.Normal,
                    fontSize = 13.sp)
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────
//  WORKS TAB
// ─────────────────────────────────────────────────────────────────

@Composable
private fun WorksTabContent(
    items: List<PortfolioItem>,
    onAddClick: () -> Unit,
    onEditClick: (PortfolioItem) -> Unit,
    onDeleteClick: (PortfolioItem) -> Unit,
    onFeatureClick: (PortfolioItem) -> Unit
) {
    Column(modifier = Modifier.padding(horizontal = 16.dp)) {

        // Header row
        Row(
            modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column {
                Text("Your Works", color = TextPrimary, fontWeight = FontWeight.Black, fontSize = 20.sp)
                Text("${items.size} piece${if (items.size != 1) "s" else ""} in your collection",
                    color = TextSecondary, fontSize = 12.sp)
            }
            // Add button
            Box(
                modifier = Modifier.clip(RoundedCornerShape(12.dp))
                    .background(Brush.horizontalGradient(listOf(GoldDeep, GoldAccent)))
                    .clickable(onClick = onAddClick).padding(horizontal = 14.dp, vertical = 8.dp)
            ) {
                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    Icon(Icons.Default.Add, null, tint = DarkSurface, modifier = Modifier.size(16.dp))
                    Text("Add Work", color = DarkSurface, fontWeight = FontWeight.Bold, fontSize = 13.sp)
                }
            }
        }

        Spacer(Modifier.height(4.dp))

        if (items.isEmpty()) {
            EmptyWorksPlaceholder(onAddClick = onAddClick)
        } else {
            // Featured works first
            val featured = items.filter { it.featured }
            val regular  = items.filter { !it.featured }

            if (featured.isNotEmpty()) {
                SectionLabel("⭐  FEATURED")
                Spacer(Modifier.height(10.dp))
                featured.forEach { item ->
                    PortfolioItemCard(item = item, onEdit = onEditClick, onDelete = onDeleteClick, onFeature = onFeatureClick)
                    Spacer(Modifier.height(12.dp))
                }
            }

            if (regular.isNotEmpty()) {
                if (featured.isNotEmpty()) SectionLabel("ALL WORKS")
                Spacer(Modifier.height(10.dp))
                regular.forEach { item ->
                    PortfolioItemCard(item = item, onEdit = onEditClick, onDelete = onDeleteClick, onFeature = onFeatureClick)
                    Spacer(Modifier.height(12.dp))
                }
            }
        }
    }
}

@Composable
private fun EmptyWorksPlaceholder(onAddClick: () -> Unit) {
    Box(
        modifier = Modifier.fillMaxWidth().height(260.dp)
            .clip(RoundedCornerShape(20.dp))
            .background(CardBackground)
            .border(1.dp, GoldPrimary.copy(0.15f), RoundedCornerShape(20.dp)),
        contentAlignment = Alignment.Center
    ) {
        Column(horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.spacedBy(12.dp)) {
            Box(modifier = Modifier.size(64.dp).clip(CircleShape)
                .background(GoldPrimary.copy(alpha = 0.1f)), contentAlignment = Alignment.Center) {
                Icon(Icons.Default.PhotoLibrary, null, tint = GoldPrimary, modifier = Modifier.size(32.dp))
            }
            Text("No works yet", color = TextPrimary, fontWeight = FontWeight.Bold, fontSize = 16.sp)
            Text("Add your first creative piece\nto start building your portfolio",
                color = TextSecondary, fontSize = 13.sp, textAlign = TextAlign.Center)
            Box(
                modifier = Modifier.clip(RoundedCornerShape(12.dp))
                    .background(Brush.horizontalGradient(listOf(GoldDeep, GoldAccent)))
                    .clickable(onClick = onAddClick).padding(horizontal = 20.dp, vertical = 10.dp)
            ) {
                Text("Add First Work", color = DarkSurface, fontWeight = FontWeight.Bold, fontSize = 14.sp)
            }
        }
    }
}

@Composable
private fun SectionLabel(text: String) {
    Text(text, color = TextSecondary, fontSize = 10.sp, fontWeight = FontWeight.Bold, letterSpacing = 2.sp)
}

@Composable
private fun PortfolioItemCard(
    item: PortfolioItem,
    onEdit: (PortfolioItem) -> Unit,
    onDelete: (PortfolioItem) -> Unit,
    onFeature: (PortfolioItem) -> Unit
) {
    Card(
        modifier  = Modifier.fillMaxWidth(),
        shape     = RoundedCornerShape(18.dp),
        colors    = CardDefaults.cardColors(containerColor = CardBackground),
        elevation = CardDefaults.cardElevation(if (item.featured) 4.dp else 1.dp),
        border    = if (item.featured) BorderStroke(1.dp, Brush.horizontalGradient(listOf(GoldDeep, GoldAccent))) else null
    ) {
        Column {
            // Image area
            Box(
                modifier = Modifier.fillMaxWidth().height(160.dp)
                    .clip(RoundedCornerShape(topStart = 18.dp, topEnd = 18.dp))
                    .background(DarkCard)
            ) {
                if (item.imageUrl.isNotEmpty()) {
                    AsyncImage(model = item.imageUrl, contentDescription = item.title,
                        contentScale = ContentScale.Crop, modifier = Modifier.fillMaxSize())
                } else {
                    // Placeholder gradient
                    Box(modifier = Modifier.fillMaxSize().background(
                        Brush.linearGradient(listOf(DarkCard, DarkSurface))
                    ), contentAlignment = Alignment.Center) {
                        Icon(Icons.Default.Image, null, tint = Color(0xFF3A3A3A), modifier = Modifier.size(40.dp))
                    }
                }
                // Category chip
                Box(modifier = Modifier.align(Alignment.TopStart).padding(12.dp)
                    .clip(RoundedCornerShape(8.dp)).background(DarkSurface.copy(0.85f))
                    .padding(horizontal = 10.dp, vertical = 4.dp)) {
                    Text(item.category.ifEmpty { "Uncategorized" }, color = GoldAccent,
                        fontSize = 10.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.sp)
                }
                // Featured star
                if (item.featured) {
                    Box(modifier = Modifier.align(Alignment.TopEnd).padding(12.dp)
                        .clip(CircleShape).background(GoldPrimary)
                        .padding(6.dp)) {
                        Icon(Icons.Default.Star, null, tint = DarkSurface, modifier = Modifier.size(12.dp))
                    }
                }
            }

            // Info row
            Column(modifier = Modifier.padding(16.dp)) {
                Text(item.title.ifEmpty { "Untitled" }, color = TextPrimary,
                    fontWeight = FontWeight.Bold, fontSize = 15.sp, maxLines = 1, overflow = TextOverflow.Ellipsis)
                if (item.description.isNotEmpty()) {
                    Spacer(Modifier.height(4.dp))
                    Text(item.description, color = TextSecondary, fontSize = 12.sp,
                        maxLines = 2, overflow = TextOverflow.Ellipsis)
                }
                if (item.tags.isNotEmpty()) {
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                        item.tags.take(3).forEach { tag ->
                            Box(modifier = Modifier.clip(RoundedCornerShape(6.dp))
                                .background(GoldPrimary.copy(0.08f))
                                .padding(horizontal = 8.dp, vertical = 3.dp)) {
                                Text("#$tag", color = GoldPrimary, fontSize = 10.sp, fontWeight = FontWeight.Medium)
                            }
                        }
                    }
                }

                Spacer(Modifier.height(12.dp))
                HorizontalDivider(color = BackgroundSecondary, thickness = 0.5.dp)
                Spacer(Modifier.height(10.dp))

                // Actions
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    // Feature toggle
                    ActionChip(
                        icon  = if (item.featured) Icons.Default.StarBorder else Icons.Default.Star,
                        label = if (item.featured) "Unfeature" else "Feature",
                        color = GoldPrimary,
                        onClick = { onFeature(item) }
                    )
                    ActionChip(icon = Icons.Default.Edit, label = "Edit",  color = SoftBlue,  onClick = { onEdit(item) })
                    ActionChip(icon = Icons.Default.Delete, label = "Remove", color = Error, onClick = { onDelete(item) })
                }
            }
        }
    }
}

@Composable
private fun ActionChip(icon: androidx.compose.ui.graphics.vector.ImageVector, label: String, color: Color, onClick: () -> Unit) {
    Box(
        modifier = Modifier.clip(RoundedCornerShape(8.dp))
            .background(color.copy(alpha = 0.10f))
            .clickable(onClick = onClick).padding(horizontal = 10.dp, vertical = 6.dp)
    ) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
            Icon(icon, null, tint = color, modifier = Modifier.size(13.dp))
            Text(label, color = color, fontSize = 11.sp, fontWeight = FontWeight.SemiBold)
        }
    }
}

// ─────────────────────────────────────────────────────────────────
//  BUILDER TAB
// ─────────────────────────────────────────────────────────────────

@Composable
private fun BuilderTabContent(
    meta: PortfolioMeta,
    isGenerating: Boolean,
    isSaving: Boolean,
    errorMsg: String,
    onMetaChange: (PortfolioMeta) -> Unit,
    onSave: () -> Unit,
    onAutoGenerate: () -> Unit
) {
    Column(modifier = Modifier.padding(horizontal = 16.dp)) {

        // Auto-generate card
        AutoGenerateCard(isGenerating = isGenerating, onGenerate = onAutoGenerate)

        Spacer(Modifier.height(20.dp))

        // Section label
        Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.padding(bottom = 14.dp)) {
            Box(Modifier.width(3.dp).height(16.dp).background(GoldGradient, RoundedCornerShape(2.dp)))
            Spacer(Modifier.width(10.dp))
            Text("CUSTOMISE YOUR PORTFOLIO", color = TextSecondary, fontSize = 10.sp,
                fontWeight = FontWeight.Bold, letterSpacing = 2.sp)
        }

        Card(
            modifier  = Modifier.fillMaxWidth(),
            shape     = RoundedCornerShape(20.dp),
            colors    = CardDefaults.cardColors(containerColor = CardBackground),
            elevation = CardDefaults.cardElevation(2.dp)
        ) {
            Column(modifier = Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {

                // Headline
                BuilderField(
                    label = "Professional Headline",
                    value = meta.headline,
                    hint  = "e.g. Designer · Visual Storyteller · Problem Solver",
                    onValueChange = { onMetaChange(meta.copy(headline = it)) }
                )

                HorizontalDivider(color = BackgroundSecondary, thickness = 0.5.dp)

                // Tagline
                BuilderField(
                    label      = "Tagline / Pitch Summary",
                    value      = meta.tagline,
                    hint       = "1–2 sentences that capture who you are and what you create",
                    singleLine = false,
                    minLines   = 3,
                    onValueChange = { onMetaChange(meta.copy(tagline = it)) }
                )

                HorizontalDivider(color = BackgroundSecondary, thickness = 0.5.dp)

                // Theme selector
                Column {
                    Text("Portfolio Theme", color = TextSecondary, fontSize = 11.sp,
                        fontWeight = FontWeight.Bold, letterSpacing = 0.5.sp)
                    Spacer(Modifier.height(10.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        listOf("dark" to "Dark", "light" to "Light", "gold" to "Gold").forEach { (value, label) ->
                            ThemeChip(
                                label     = label,
                                isSelected = meta.theme == value,
                                color     = when (value) {
                                    "dark"  -> DarkSurface
                                    "light" -> BackgroundMain
                                    else    -> GoldPrimary
                                },
                                onClick   = { onMetaChange(meta.copy(theme = value)) }
                            )
                        }
                    }
                }
            }
        }

        // Error
        AnimatedVisibility(visible = errorMsg.isNotEmpty(), enter = fadeIn(), exit = fadeOut()) {
            Spacer(Modifier.height(12.dp))
            Row(
                modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(10.dp))
                    .background(Error.copy(0.08f)).padding(12.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Icon(Icons.Default.ErrorOutline, null, tint = Error, modifier = Modifier.size(14.dp))
                Spacer(Modifier.width(8.dp))
                Text(errorMsg, style = MaterialTheme.typography.bodySmall.copy(color = Error))
            }
        }

        Spacer(Modifier.height(20.dp))

        // Save button
        Box(
            modifier = Modifier.fillMaxWidth().height(54.dp)
                .clip(RoundedCornerShape(16.dp))
                .background(Brush.horizontalGradient(listOf(GoldDeep, GoldAccent)))
                .clickable(enabled = !isSaving, onClick = onSave),
            contentAlignment = Alignment.Center
        ) {
            AnimatedContent(targetState = isSaving, label = "save_btn") { saving ->
                if (saving) {
                    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        CircularProgressIndicator(color = DarkSurface, strokeWidth = 2.dp, modifier = Modifier.size(18.dp))
                        Text("Saving…", color = DarkSurface, fontWeight = FontWeight.Bold)
                    }
                } else {
                    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Icon(Icons.Default.Save, null, tint = DarkSurface, modifier = Modifier.size(18.dp))
                        Text("Save Portfolio", color = DarkSurface, fontWeight = FontWeight.Black, fontSize = 15.sp)
                    }
                }
            }
        }
    }
}

@Composable
private fun AutoGenerateCard(isGenerating: Boolean, onGenerate: () -> Unit) {
    val shimmer by rememberInfiniteTransition(label = "shimmer").animateFloat(
        initialValue = 0f, targetValue = 1f,
        animationSpec = infiniteRepeatable(tween(1800, easing = LinearEasing)), label = "s"
    )

    Box(
        modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(20.dp))
            .background(Brush.linearGradient(listOf(DarkCard, DarkSurface)))
            .border(1.dp, GoldPrimary.copy(0.35f), RoundedCornerShape(20.dp))
    ) {
        // Subtle gold glow
        Canvas(Modifier.matchParentSize()) {
            drawCircle(
                brush = Brush.radialGradient(listOf(GoldPrimary.copy(0.12f), Color.Transparent),
                    center = Offset(size.width * 0.15f, size.height * 0.2f), radius = size.width * 0.5f)
            )
        }
        Column(modifier = Modifier.padding(20.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                Box(modifier = Modifier.size(40.dp).clip(CircleShape)
                    .background(GoldPrimary.copy(0.15f)), contentAlignment = Alignment.Center) {
                    Text("✨", fontSize = 20.sp)
                }
                Column {
                    Text("Auto-Generate Portfolio", color = TextOnDark, fontWeight = FontWeight.Black, fontSize = 15.sp)
                    Text("Built from your profile & uploads", color = TextOnDark.copy(0.5f), fontSize = 12.sp)
                }
            }
            Spacer(Modifier.height(14.dp))
            Text(
                "Let Forge analyse your profile, profession, bio, and uploads to craft a polished portfolio identity for you — instantly.",
                color = TextOnDark.copy(0.7f), fontSize = 13.sp, lineHeight = 19.sp
            )
            Spacer(Modifier.height(16.dp))
            Box(
                modifier = Modifier.fillMaxWidth().height(48.dp).clip(RoundedCornerShape(14.dp))
                    .background(Brush.horizontalGradient(listOf(GoldDeep, GoldAccent)))
                    .clickable(enabled = !isGenerating, onClick = onGenerate),
                contentAlignment = Alignment.Center
            ) {
                AnimatedContent(targetState = isGenerating, label = "gen_btn") { gen ->
                    if (gen) {
                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            CircularProgressIndicator(color = DarkSurface, strokeWidth = 2.dp, modifier = Modifier.size(16.dp))
                            Text("Generating…", color = DarkSurface, fontWeight = FontWeight.Bold)
                        }
                    } else {
                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text("✨", fontSize = 16.sp)
                            Text("Auto-Generate Now", color = DarkSurface, fontWeight = FontWeight.Black, fontSize = 14.sp)
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun BuilderField(
    label: String, value: String, hint: String,
    singleLine: Boolean = true, minLines: Int = 1,
    onValueChange: (String) -> Unit
) {
    val isFilled = value.isNotEmpty()
    Column {
        Text(label, color = if (isFilled) GoldPrimary else TextSecondary,
            fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 0.4.sp)
        TextField(
            value = value, onValueChange = onValueChange,
            placeholder = { Text(hint, style = MaterialTheme.typography.bodyMedium.copy(color = Color(0xFFBBBBBB), fontSize = 14.sp)) },
            singleLine = singleLine, minLines = minLines,
            colors = TextFieldDefaults.colors(
                focusedContainerColor = Color.Transparent, unfocusedContainerColor = Color.Transparent,
                focusedIndicatorColor = Color.Transparent, unfocusedIndicatorColor = Color.Transparent,
                focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary, cursorColor = GoldPrimary
            ),
            textStyle = MaterialTheme.typography.bodyMedium.copy(color = TextPrimary, fontSize = 14.sp),
            modifier = Modifier.fillMaxWidth()
        )
        Box(modifier = Modifier.fillMaxWidth().height(if (isFilled) 1.5.dp else 1.dp)
            .background(if (isFilled) GoldGradient else Brush.linearGradient(listOf(BackgroundSecondary, BackgroundSecondary))))
    }
}

@Composable
private fun ThemeChip(label: String, isSelected: Boolean, color: Color, onClick: () -> Unit) {
    Box(
        modifier = Modifier.clip(RoundedCornerShape(10.dp))
            .background(if (isSelected) GoldPrimary.copy(0.12f) else BackgroundSecondary)
            .border(if (isSelected) 1.5.dp else 0.dp,
                if (isSelected) GoldPrimary else Color.Transparent, RoundedCornerShape(10.dp))
            .clickable(onClick = onClick).padding(horizontal = 14.dp, vertical = 8.dp)
    ) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(6.dp)) {
            Box(modifier = Modifier.size(14.dp).clip(CircleShape).background(color)
                .border(1.dp, GoldPrimary.copy(0.3f), CircleShape))
            Text(label, color = if (isSelected) GoldPrimary else TextSecondary,
                fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal, fontSize = 13.sp)
        }
    }
}

// ─────────────────────────────────────────────────────────────────
//  PREVIEW TAB
// ─────────────────────────────────────────────────────────────────

@Composable
private fun PreviewTabContent(
    meta: PortfolioMeta,
    items: List<PortfolioItem>,
    onPitchClick: () -> Unit
) {
    Column(modifier = Modifier.padding(horizontal = 16.dp)) {

        // Live preview card
        Card(
            modifier  = Modifier.fillMaxWidth(),
            shape     = RoundedCornerShape(20.dp),
            colors    = CardDefaults.cardColors(containerColor = if (meta.theme == "dark") DarkCard else CardBackground),
            elevation = CardDefaults.cardElevation(4.dp)
        ) {
            Column {
                // Cover gradient
                Box(
                    modifier = Modifier.fillMaxWidth().height(140.dp)
                        .clip(RoundedCornerShape(topStart = 20.dp, topEnd = 20.dp))
                        .background(
                            when (meta.theme) {
                                "dark"  -> Brush.linearGradient(listOf(DarkSurface, DarkCard))
                                "gold"  -> Brush.linearGradient(listOf(GoldDeep, GoldAccent))
                                else    -> Brush.linearGradient(listOf(BackgroundSecondary, BackgroundMain))
                            }
                        )
                ) {
                    Canvas(Modifier.matchParentSize()) {
                        val spacing = 28f
                        val cols = (size.width / spacing).toInt() + 2
                        val rows = (size.height / spacing).toInt() + 2
                        for (c in 0..cols) for (r in 0..rows) {
                            drawCircle(GoldPrimary.copy(0.06f), 1.4f, Offset(c * spacing.toFloat(), r * spacing.toFloat()))
                        }
                    }
                    Column(modifier = Modifier.align(Alignment.BottomStart).padding(20.dp)) {
                        if (meta.headline.isNotEmpty()) {
                            Text(meta.headline, color = if (meta.theme == "gold") DarkSurface else TextOnDark,
                                fontWeight = FontWeight.Black, fontSize = 14.sp, maxLines = 2, overflow = TextOverflow.Ellipsis)
                        }
                    }
                }

                // Tagline
                if (meta.tagline.isNotEmpty()) {
                    Text(
                        meta.tagline,
                        color    = if (meta.theme == "dark") TextOnDark.copy(0.75f) else TextSecondary,
                        fontSize = 13.sp, lineHeight = 19.sp,
                        modifier = Modifier.padding(horizontal = 20.dp, vertical = 16.dp)
                    )
                }

                HorizontalDivider(color = BackgroundSecondary.copy(0.4f))

                // Featured works thumbnails
                val featured = items.filter { it.featured }.take(3)
                if (featured.isNotEmpty()) {
                    Text("Featured Works", color = if (meta.theme == "dark") GoldAccent else GoldPrimary,
                        fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.sp,
                        modifier = Modifier.padding(start = 20.dp, top = 14.dp))
                    Row(modifier = Modifier.padding(horizontal = 16.dp, vertical = 10.dp),
                        horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        featured.forEach { item ->
                            Box(modifier = Modifier.size(72.dp).clip(RoundedCornerShape(12.dp))
                                .background(DarkSurface)) {
                                if (item.imageUrl.isNotEmpty()) {
                                    AsyncImage(model = item.imageUrl, contentDescription = item.title,
                                        contentScale = ContentScale.Crop, modifier = Modifier.fillMaxSize())
                                } else {
                                    Box(modifier = Modifier.fillMaxSize().background(
                                        Brush.linearGradient(listOf(DarkCard, Color(0xFF2A2A2A)))),
                                        contentAlignment = Alignment.Center) {
                                        Icon(Icons.Default.Image, null, tint = Color(0xFF444444), modifier = Modifier.size(24.dp))
                                    }
                                }
                            }
                        }
                    }
                }

                Spacer(Modifier.height(8.dp))

                // Stats strip
                Row(modifier = Modifier.fillMaxWidth().padding(horizontal = 20.dp, vertical = 8.dp),
                    horizontalArrangement = Arrangement.SpaceBetween) {
                    listOf("${items.size}" to "Works", "${items.count { it.featured }}" to "Featured",
                        if (meta.isPublished) "Live" to "Status" else "Draft" to "Status").forEach { (val_, lbl) ->
                        Column(horizontalAlignment = Alignment.CenterHorizontally) {
                            Text(val_, color = if (meta.theme == "dark") TextOnDark else TextPrimary,
                                fontWeight = FontWeight.Black, fontSize = 16.sp)
                            Text(lbl, color = if (meta.theme == "dark") TextOnDark.copy(0.4f) else TextSecondary,
                                fontSize = 11.sp)
                        }
                    }
                }
                Spacer(Modifier.height(8.dp))
            }
        }

        Spacer(Modifier.height(20.dp))

        // Completeness indicator
        CompletenessCard(meta = meta, itemCount = items.size)

        Spacer(Modifier.height(20.dp))

        // ── PITCH BUTTON ──────────────────────────────────────────
        Box(
            modifier = Modifier.fillMaxWidth().height(58.dp).clip(RoundedCornerShape(18.dp))
                .background(Brush.horizontalGradient(listOf(GoldDeep, GoldAccent)))
                .clickable(onClick = onPitchClick),
            contentAlignment = Alignment.Center
        ) {
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                Icon(Icons.Default.Mic, null, tint = DarkSurface, modifier = Modifier.size(20.dp))
                Text("Go to Pitch View", color = DarkSurface, fontWeight = FontWeight.Black, fontSize = 15.sp, letterSpacing = 0.3.sp)
                Icon(Icons.AutoMirrored.Filled.ArrowForward, null, tint = DarkSurface, modifier = Modifier.size(18.dp))
            }
        }

        Spacer(Modifier.height(10.dp))

        Text(
            "Your portfolio will be attached to your pitch deck automatically",
            color = TextSecondary, fontSize = 12.sp, textAlign = TextAlign.Center,
            modifier = Modifier.fillMaxWidth()
        )
    }
}

@Composable
private fun CompletenessCard(meta: PortfolioMeta, itemCount: Int) {
    val checks = listOf(
        "Headline added"      to meta.headline.isNotBlank(),
        "Tagline written"     to meta.tagline.isNotBlank(),
        "Works uploaded"      to (itemCount > 0),
        "Featured work set"   to (itemCount > 0),  // simplification; a real check would look at featured flag
        "Portfolio published" to meta.isPublished
    )
    val score = checks.count { it.second }.toFloat() / checks.size

    Card(
        modifier  = Modifier.fillMaxWidth(),
        shape     = RoundedCornerShape(16.dp),
        colors    = CardDefaults.cardColors(containerColor = CardBackground),
        elevation = CardDefaults.cardElevation(1.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically) {
                Text("Portfolio Completeness", color = TextPrimary, fontWeight = FontWeight.Bold, fontSize = 13.sp)
                Text("${(score * 100).toInt()}%", color = GoldPrimary, fontWeight = FontWeight.Black, fontSize = 15.sp)
            }
            Spacer(Modifier.height(8.dp))
            LinearProgressIndicator(
                progress   = { score },
                modifier   = Modifier.fillMaxWidth().height(6.dp).clip(RoundedCornerShape(3.dp)),
                color      = GoldPrimary,
                trackColor = BackgroundSecondary
            )
            Spacer(Modifier.height(12.dp))
            checks.forEach { (label, done) ->
                Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.padding(vertical = 3.dp)) {
                    Icon(
                        if (done) Icons.Default.CheckCircle else Icons.Default.RadioButtonUnchecked,
                        null,
                        tint = if (done) SoftGreen else Color(0xFFCCC5B8),
                        modifier = Modifier.size(16.dp)
                    )
                    Spacer(Modifier.width(8.dp))
                    Text(label, color = if (done) TextPrimary else TextSecondary, fontSize = 12.sp)
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────
//  ADD / EDIT ITEM DIALOG
// ─────────────────────────────────────────────────────────────────

@Composable
private fun AddEditItemDialog(
    initial: PortfolioItem?,
    onDismiss: () -> Unit,
    onSave: (PortfolioItem) -> Unit
) {
    var title       by remember { mutableStateOf(initial?.title ?: "") }
    var category    by remember { mutableStateOf(initial?.category ?: "") }
    var description by remember { mutableStateOf(initial?.description ?: "") }
    var imageUrl    by remember { mutableStateOf(initial?.imageUrl ?: "") }
    var tagsRaw     by remember { mutableStateOf(initial?.tags?.joinToString(", ") ?: "") }
    var showError   by remember { mutableStateOf(false) }

    Dialog(onDismissRequest = onDismiss, properties = DialogProperties(usePlatformDefaultWidth = false)) {
        Box(
            modifier = Modifier.fillMaxSize().background(Color.Black.copy(0.6f))
                .clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = onDismiss),
            contentAlignment = Alignment.BottomCenter
        ) {
            Column(
                modifier = Modifier.fillMaxWidth()
                    .clip(RoundedCornerShape(topStart = 28.dp, topEnd = 28.dp))
                    .background(CardBackground)
                    .clickable(interactionSource = remember { MutableInteractionSource() }, indication = null) {}
                    .padding(24.dp)
                    .verticalScroll(rememberScrollState())
            ) {
                // Handle
                Box(modifier = Modifier.align(Alignment.CenterHorizontally).width(40.dp).height(4.dp)
                    .clip(CircleShape).background(Color(0xFFDDD8CE)))
                Spacer(Modifier.height(16.dp))

                Text(if (initial == null) "Add Work" else "Edit Work",
                    color = TextPrimary, fontWeight = FontWeight.Black, fontSize = 18.sp)
                Spacer(Modifier.height(4.dp))
                Text("Fill in the details for this portfolio piece",
                    color = TextSecondary, fontSize = 13.sp)
                Spacer(Modifier.height(20.dp))

                DialogField("Title *", title, "e.g. Brand Identity – Forge", showError && title.isBlank()) { title = it }
                Spacer(Modifier.height(14.dp))
                DialogField("Category", category, "e.g. Branding, Motion, Photography") { category = it }
                Spacer(Modifier.height(14.dp))
                DialogField("Description", description, "What is this project about?", singleLine = false, minLines = 3) { description = it }
                Spacer(Modifier.height(14.dp))
                DialogField("Image URL (Cloudinary)", imageUrl, "https://res.cloudinary.com/...") { imageUrl = it }
                Spacer(Modifier.height(14.dp))
                DialogField("Tags (comma separated)", tagsRaw, "e.g. ui, branding, print") { tagsRaw = it }

                if (showError && title.isBlank()) {
                    Spacer(Modifier.height(10.dp))
                    Text("Title is required", color = Error, fontSize = 12.sp)
                }

                Spacer(Modifier.height(24.dp))

                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    OutlinedButton(
                        onClick = onDismiss, modifier = Modifier.weight(1f).height(48.dp),
                        shape = RoundedCornerShape(14.dp)
                    ) { Text("Cancel", color = TextSecondary) }

                    Box(
                        modifier = Modifier.weight(1f).height(48.dp).clip(RoundedCornerShape(14.dp))
                            .background(Brush.horizontalGradient(listOf(GoldDeep, GoldAccent)))
                            .clickable {
                                if (title.isBlank()) { showError = true; return@clickable }
                                val tags = tagsRaw.split(",").map { it.trim() }.filter { it.isNotEmpty() }
                                onSave(
                                    (initial ?: PortfolioItem()).copy(
                                        title       = title.trim(),
                                        category    = category.trim(),
                                        description = description.trim(),
                                        imageUrl    = imageUrl.trim(),
                                        tags        = tags
                                    )
                                )
                            },
                        contentAlignment = Alignment.Center
                    ) {
                        Text(if (initial == null) "Add to Portfolio" else "Save Changes",
                            color = DarkSurface, fontWeight = FontWeight.Black, fontSize = 14.sp)
                    }
                }

                Spacer(Modifier.height(24.dp))
            }
        }
    }
}

@Composable
private fun DialogField(
    label: String, value: String, hint: String,
    showError: Boolean = false, singleLine: Boolean = true, minLines: Int = 1,
    onValueChange: (String) -> Unit
) {
    val isFilled = value.isNotEmpty()
    Column {
        Text(label,
            color = when { showError -> Error; isFilled -> GoldPrimary; else -> TextSecondary },
            fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 0.4.sp)
        TextField(
            value = value, onValueChange = onValueChange,
            placeholder = { Text(hint, style = MaterialTheme.typography.bodyMedium.copy(color = Color(0xFFBBBBBB), fontSize = 13.sp)) },
            singleLine = singleLine, minLines = minLines,
            colors = TextFieldDefaults.colors(
                focusedContainerColor = Color.Transparent, unfocusedContainerColor = Color.Transparent,
                focusedIndicatorColor = Color.Transparent, unfocusedIndicatorColor = Color.Transparent,
                focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary, cursorColor = GoldPrimary
            ),
            textStyle = MaterialTheme.typography.bodyMedium.copy(color = TextPrimary, fontSize = 14.sp),
            modifier = Modifier.fillMaxWidth()
        )
        Box(modifier = Modifier.fillMaxWidth().height(if (showError) 1.5.dp else 1.dp)
            .background(when { showError -> Brush.linearGradient(listOf(Error, Error.copy(0.6f)));
                isFilled -> GoldGradient; else -> Brush.linearGradient(listOf(BackgroundSecondary, BackgroundSecondary)) }))
    }
}

// ─────────────────────────────────────────────────────────────────
//  CANVAS HELPERS
// ─────────────────────────────────────────────────────────────────

private fun DrawScope.drawDots(color: Color, spacing: Float) {
    val cols = (size.width / spacing).toInt() + 2
    val rows = (size.height / spacing).toInt() + 2
    for (c in 0..cols) for (r in 0..rows)
        drawCircle(color, 1.4f, Offset(c * spacing, r * spacing))
}

// ─────────────────────────────────────────────────────────────────
//  PREVIEW
// ─────────────────────────────────────────────────────────────────

@Preview(showBackground = true, showSystemUi = true)
@Composable
fun PortfolioBuilderScreenPreview() {
    PortfolioBuilderScreen(rememberNavController())
}