package com.kennedy.forge.navigation

const val ROUTE_SPLASH = "splash"
const val ROUTE_Register = "register"
const val ROUTE_Login = "login"
const val ROUT_ONBOARDING1 = "onboarding1"
const val ROUT_ONBOARDING2 = "onboarding2"
const val ROUT_ONBOARDING3 = "onboarding3"
const val ROUT_ProfileSetup = "profileSetup"
const val ROUT_SkillAssessment = "SkillAssessment"
const val ROUT_Dashboard = "Dashboard"
const val ROUT_SubmitWork = "SubmitWork"
const val ROUT_FeedbackDashboard = "FeedbackDashboard"
const val ROUT_ProjectDetail = "ProjectDetail"
const val ROUT_Profile = "Profile"
const val ROUT_DiscoveryFeed = "DiscoveryFeed"
const val ROUT_EditProject = "EditProject"
const val ROUT_Collaboration = "Collaboration"
const val ROUT_PublicProfile = "PublicProfile"
const val ROUT_Notification = "Notification"
const val ROUT_PitchView= "PitchView"
const val ROUT_Search= "Search"
const val ROUT_Payments= "Payments"
const val ROUT_Security= "Security"
const val ROUT_GrowthInsight= "GrowthInsight"
const val ROUT_PortfolioBuilder= "PortfolioBuilder"
const val ROUT_BlockDiagnosis= "BlockDiagnosis"
const val ROUT_Settings= "Settings"

const val ROUT_Privacy= "Privacy"
const val ROUT_ChangePassword= "ChangePassword"

